" BASIC SETUP
set nocompatible
set number
set autoindent
filetype plugin on

" SET COLORS
syntax enable
colorscheme monokai

" FILE FINDER (:find)
set path+=**
set wildmenu

" Plugins
call plug#begin('~/.vim/plugged')
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes;
call plug#end()
